// Zodiac content for the local wisdom engine. Each sign carries its structural
// signature (element, modality, ruler) plus prose written for the four chart
// roles the app tracks: Sun (identity), Moon (inner life), Rising (persona),
// and North Node (growth). No API — this is the source the readings compose from.

export const ZODIAC = {
  Aries: {
    element: "Fire", modality: "Cardinal", polarity: "Yang", ruler: "Mars",
    keywords: ["initiative", "courage", "directness", "drive"],
    gift: "the nerve to begin before you feel ready and to move without waiting for permission",
    shadow: "impatience that starts a hundred fires and tends none of them to completion",
    sun: "Your identity is built around the first move. You come alive at the starting line, and you would rather act and correct course than deliberate yourself into paralysis. The work of a lifetime is learning that finishing is its own kind of courage.",
    moon: "Emotionally you need immediacy. Feelings arrive fast and hot and pass just as quickly; what wounds you is being made to wait or being managed. You soothe yourself through motion and honest confrontation, not through sitting with it.",
    rising: "You arrive in a room like a decision already made. People read you as bold, a little impatient, quick to engage. Your first instinct is to lead, and others feel that before you say a word.",
    node: "Your growth asks you to reclaim your own wants after a lifetime of accommodating everyone else's. The lesson is healthy self-assertion, doing the thing you want without first taking a survey.",
  },
  Taurus: {
    element: "Earth", modality: "Fixed", polarity: "Yin", ruler: "Venus",
    keywords: ["steadiness", "sensuality", "loyalty", "patience"],
    gift: "the ability to build something real, slowly, and make it last",
    shadow: "a stubbornness that mistakes not-moving for being grounded",
    sun: "Your identity is rooted in what is tangible, reliable, and enjoyed. You measure a life by what you can actually rest your weight against. Your gift is endurance; your edge is knowing when holding steady has become refusing to change.",
    moon: "You need security you can feel: a stable home, a predictable rhythm, physical comfort. Change unsettles you at a bodily level, and you settle through the senses, good food, warmth, familiar hands, familiar ground.",
    rising: "You come across as calm, solid, unhurried. People trust that you will not flinch. There is a sensual, grounded quality to your presence that makes others slow down around you.",
    node: "Your path is toward your own values and resources, away from being pulled into other people's intensities and crises. You are learning to build self-worth that does not depend on someone else's storm.",
  },
  Gemini: {
    element: "Air", modality: "Mutable", polarity: "Yang", ruler: "Mercury",
    keywords: ["curiosity", "wit", "adaptability", "connection"],
    gift: "a mind that can hold many things at once and translate between worlds",
    shadow: "scattering yourself so thin that nothing goes deep",
    sun: "Your identity is language, curiosity, and the constant crossing of ideas. You are here to gather, connect, and pass things along. Your challenge is depth: choosing the one conversation worth staying inside long enough to change you.",
    moon: "You process feeling by talking and thinking it through; an unspoken emotion barely feels real to you yet. You need mental stimulation and variety to feel safe, and restlessness is often your grief in disguise.",
    rising: "You seem quick, verbal, youthful, endlessly interested. People find you easy to talk to and hard to pin down. Your curiosity is the first thing anyone meets.",
    node: "Your growth is toward listening and the ground-level truth, away from collecting opinions and abstractions. You are learning to trust what is directly in front of you.",
  },
  Cancer: {
    element: "Water", modality: "Cardinal", polarity: "Yin", ruler: "Moon",
    keywords: ["nurture", "memory", "protection", "feeling"],
    gift: "the capacity to make anyone feel held, remembered, and safe",
    shadow: "clinging to what hurt you and calling the shell a home",
    sun: "Your identity is care and emotional memory. You lead through tenderness and you protect fiercely what is yours. Your work is to give that same devotion to yourself, and to let people close without needing to mother them.",
    moon: "This is the Moon at home. You feel everything, deeply and in tides, and you carry the emotional weather of a whole room. You need a safe nest and people who let you retreat into your shell without taking it personally.",
    rising: "You come across as gentle, guarded, quietly perceptive. People sense they are being taken care of. It can take time before you let someone past the outer shell.",
    node: "Your path leads home, into your feelings and private life, away from over-managing your public standing and reputation. You are learning that being nourished matters as much as being accomplished.",
  },
  Leo: {
    element: "Fire", modality: "Fixed", polarity: "Yang", ruler: "Sun",
    keywords: ["warmth", "creativity", "pride", "generosity"],
    gift: "a heart that warms a room and dares to be fully seen",
    shadow: "needing the applause so badly that you perform instead of live",
    sun: "This is the Sun at home. Your identity is radiance, creativity, and heart. You are here to shine, to create, to love generously and be loved back. The lesson is a self-worth that does not require the audience to keep clapping.",
    moon: "You need to feel special, seen, and appreciated to feel emotionally safe. Warmth restores you; being ignored or diminished wounds you deeply. You love with your whole chest and need that met in kind.",
    rising: "You enter with presence, warmth, and a certain dignity. People notice you and remember you. There is drama and generosity in how you carry yourself.",
    node: "Your growth is toward the individual heart and creative courage, away from hiding inside the crowd and its causes. You are learning to stand up as yourself, not just as a member of the group.",
  },
  Virgo: {
    element: "Earth", modality: "Mutable", polarity: "Yin", ruler: "Mercury",
    keywords: ["discernment", "service", "craft", "precision"],
    gift: "the eye that sees exactly what needs fixing and the hands to do it",
    shadow: "a perfectionism that turns care into constant criticism",
    sun: "Your identity is refinement and useful service. You see the flaw, the improvement, the better way, and you are compelled to help. Your work is offering that gift without turning it on yourself as relentless self-critique.",
    moon: "You feel safe when things are in order and you can be useful. Anxiety is your body's way of trying to prevent harm. You settle by doing something concrete, tidying, tending, solving, and by being gentle with your own imperfection.",
    rising: "You seem composed, modest, quietly competent. People sense you notice the details they miss. There is a helpful, unpretentious quality to your presence.",
    node: "Your path is toward the practical, the daily, the well-tended detail, away from escapism and losing yourself in the fog. You are learning that devotion lives in small, concrete acts.",
  },
  Libra: {
    element: "Air", modality: "Cardinal", polarity: "Yang", ruler: "Venus",
    keywords: ["harmony", "fairness", "relationship", "grace"],
    gift: "the art of holding two truths in balance and making beauty of the space between",
    shadow: "losing your own position while trying to keep everyone comfortable",
    sun: "Your identity is relationship, fairness, and beauty. You think in terms of the other person and the balance between. Your work is finding your own weight in the scale so that harmony is not just self-erasure with good manners.",
    moon: "You need peace, fairness, and a sense of connection to feel safe; conflict registers in your body as genuine distress. You settle through beauty, reconciliation, and the company of someone who feels like an equal.",
    rising: "You come across as gracious, pleasant, and diplomatic. People find you charming and easy to be around. There is an instinct to accommodate and to smooth things over.",
    node: "Your growth is toward genuine partnership and cooperation, away from a hard-won self-reliance that has quietly become isolation. You are learning to let someone matter.",
  },
  Scorpio: {
    element: "Water", modality: "Fixed", polarity: "Yin", ruler: "Pluto (Mars)",
    keywords: ["intensity", "depth", "transformation", "loyalty"],
    gift: "the courage to go where others will not look and come back changed",
    shadow: "control and suspicion that guard a wound no one is allowed to touch",
    sun: "Your identity is depth and transformation. You are drawn to what is hidden, taboo, and true, and you cannot live at the surface. Your work is trusting enough to be vulnerable, so your power heals rather than merely defends.",
    moon: "You feel everything at maximum intensity and hide most of it. You need emotional truth and absolute loyalty, and betrayal marks you for a long time. You settle only when you can trust completely, which is rare and sacred.",
    rising: "You come across as magnetic, private, hard to read. People feel your intensity before they understand it. You reveal yourself slowly, if at all.",
    node: "Your path is toward surrender, intimacy, and shared depth, away from clinging to comfort, control, and what you own. You are learning to let go and be transformed.",
  },
  Sagittarius: {
    element: "Fire", modality: "Mutable", polarity: "Yang", ruler: "Jupiter",
    keywords: ["freedom", "meaning", "honesty", "expansion"],
    gift: "an appetite for meaning that turns every experience into a wider horizon",
    shadow: "running toward the next thing to avoid sitting with this one",
    sun: "Your identity is the search for meaning and freedom. You need room to roam, literally and philosophically, and you are honest to a fault. Your work is grounding the vision, staying long enough to live the truth you preach.",
    moon: "You need freedom and optimism to feel safe; being caged or made small suffocates you. You settle through movement, learning, and faith that it will work out. Restlessness is how your sadness travels.",
    rising: "You seem open, enthusiastic, and frank. People find you refreshing and a little untamed. There is a restless, adventurous quality to how you meet the world.",
    node: "Your growth is toward your own intuition and inner truth, away from endlessly gathering other people's information and opinions. You are learning to trust the knowing you already carry.",
  },
  Capricorn: {
    element: "Earth", modality: "Cardinal", polarity: "Yin", ruler: "Saturn",
    keywords: ["mastery", "responsibility", "endurance", "integrity"],
    gift: "the discipline to build something that outlasts you",
    shadow: "measuring your worth only by what you achieve",
    sun: "Your identity is mastery and responsibility. You are built for the long climb and you carry weight others cannot. Your work is remembering that you are worthy before the summit, that the mountain is not the same thing as your soul.",
    moon: "You feel safe when you are competent and in control; vulnerability feels dangerous and slightly shameful. You settle through structure, achievement, and quiet self-sufficiency, and you are learning it is safe to need people.",
    rising: "You come across as serious, capable, and reserved. People trust you with responsibility instinctively. There is a maturity and restraint in how you present yourself.",
    node: "Your path is toward self-mastery and public contribution, away from hiding inside the family, the feelings, and the familiar. You are learning to stand as an authority in your own right.",
  },
  Aquarius: {
    element: "Air", modality: "Fixed", polarity: "Yang", ruler: "Uranus (Saturn)",
    keywords: ["individuality", "vision", "detachment", "humanity"],
    gift: "the perspective to see the future the rest of us have not caught up to",
    shadow: "detachment that keeps you safely above the mess of being human",
    sun: "Your identity is individuality and the larger vision. You think in systems and futures, and you refuse to belong to a group merely to belong. Your work is bringing that vision down into warm, personal, present connection.",
    moon: "You feel safest with some emotional distance and the freedom to be different. Intense closeness can spook you. You settle through friendship, ideas, and belonging to something larger than any one relationship.",
    rising: "You come across as original, friendly, and slightly apart. People find you interesting and hard to categorize. There is a cool, inventive quality to your presence.",
    node: "Your growth is toward community and the collective, away from performing for personal recognition. You are learning that you belong to something bigger than your own spotlight.",
  },
  Pisces: {
    element: "Water", modality: "Mutable", polarity: "Yin", ruler: "Neptune (Jupiter)",
    keywords: ["compassion", "imagination", "surrender", "spirit"],
    gift: "a permeable heart that feels the whole and turns it into art and mercy",
    shadow: "dissolving your boundaries until you cannot find where you end",
    sun: "Your identity is compassion, imagination, and spiritual longing. You feel the unity beneath the separations, and the ordinary world can feel too coarse. Your work is boundaries: staying embodied enough to give your gift without drowning.",
    moon: "You are porous; you absorb the emotional field around you and cannot always tell which feelings are yours. You need solitude, water, music, and retreat to reset. You settle by returning to something larger and merciful.",
    rising: "You come across as gentle, dreamy, and hard to define. People feel understood around you without knowing why. There is a soft, otherworldly quality to your presence.",
    node: "Your path is toward faith, compassion, and surrender, away from over-analysis and the need to have everything solved and sorted. You are learning to trust the current.",
  },
};

export const ELEMENT_TEMPERAMENT = {
  Fire: "You run on inspiration, spontaneity, and the heat of what excites you.",
  Earth: "You run on the tangible: results you can touch, bodies, seasons, and time.",
  Air: "You run on ideas, language, and the connections between minds.",
  Water: "You run on feeling, intuition, and the tides beneath the surface.",
};

export const MODALITY_MODE = {
  Cardinal: "You initiate. You are at your best starting things and setting direction.",
  Fixed: "You sustain. You are at your best holding, deepening, and seeing things through.",
  Mutable: "You adapt. You are at your best adjusting, translating, and bridging change.",
};
