// Original prompts using common Western tropical sign correspondences.
import { signAttributes } from '@/lib/resonance/astrology';
export { ELEMENT_TEMPERAMENT, MODALITY_MODE } from './astrology';

const SIGNS = {
  Aries: { keywords: ['courage', 'initiative', 'directness'], gift: 'the courage to begin', shadow: 'urgency that leaves little room to choose', style: 'direct action and a willingness to begin', question: 'Where would a considered first step help more than rushing?', practice: 'Choose a first step small enough to finish without overriding your limits.' },
  Taurus: { keywords: ['steadiness', 'enjoyment', 'sustenance'], gift: 'steadiness that makes room for enjoyment', shadow: 'holding on after something stops supporting you', style: 'a steady pace and attention to tangible support', question: 'What supports you now, and what are you keeping only because it is familiar?', practice: 'Notice one ordinary source of comfort and one routine you are free to reconsider.' },
  Gemini: { keywords: ['curiosity', 'exchange', 'learning'], gift: 'curiosity that makes another perspective possible', shadow: 'collecting more information than you can use', style: 'questions, exchange, and several possible perspectives', question: 'Which question would help you decide what to do next?', practice: 'Ask one useful question, then give yourself time to consider the answer.' },
  Cancer: { keywords: ['care', 'belonging', 'memory'], gift: 'care that includes your own needs', shadow: 'taking responsibility for everyone else’s feelings', style: 'attention to care, memory, and belonging', question: 'What would care look like if your needs counted equally?', practice: 'Name a need of your own before agreeing to care for someone else.' },
  Leo: { keywords: ['creativity', 'warmth', 'expression'], gift: 'warmth and the willingness to create', shadow: 'letting approval decide what you express', style: 'creative expression and a wish to participate wholeheartedly', question: 'What would you make or share even without applause?', practice: 'Give a few minutes to making something for your own enjoyment.' },
  Virgo: { keywords: ['discernment', 'craft', 'care'], gift: 'care expressed through useful attention', shadow: 'turning improvement into relentless self-criticism', style: 'careful observation and workable improvements', question: 'What is one useful improvement, and when will it be enough?', practice: 'Set a reasonable stopping point for one task before beginning it.' },
  Libra: { keywords: ['fairness', 'relationship', 'perspective'], gift: 'fairness that leaves room for an honest difference', shadow: 'keeping peace at the expense of your own limits', style: 'attention to reciprocity, balance, and another point of view', question: 'Is this agreement fair to you as well as to the other person?', practice: 'Write down your preference before negotiating or deciding whether to participate.' },
  Scorpio: { keywords: ['depth', 'honesty', 'discernment'], gift: 'the willingness to look beneath an easy explanation', shadow: 'searching for certainty through control', style: 'depth, privacy, and close attention to trust', question: 'What do you know from experience, and what remains an assumption?', practice: 'Separate what happened from what you fear it means. Keep the boundary you need.' },
  Sagittarius: { keywords: ['exploration', 'meaning', 'perspective'], gift: 'a wider perspective that remains open to learning', shadow: 'letting a large belief outrun the facts', style: 'exploration and a search for a larger meaning', question: 'Which belief expands your options, and which one needs questioning?', practice: 'Explore an unfamiliar perspective without committing to its conclusions.' },
  Capricorn: { keywords: ['commitment', 'skill', 'responsibility'], gift: 'patient effort toward something you value', shadow: 'measuring your worth only by what you accomplish', style: 'longer horizons, responsibility, and practical effort', question: 'Which responsibility is yours, and which could you put down?', practice: 'Choose one realistic commitment and protect time outside it.' },
  Aquarius: { keywords: ['originality', 'community', 'independence'], gift: 'independent thought with room for other people', shadow: 'using distance to avoid your own needs', style: 'independent thinking and attention to the wider community', question: 'How can you belong without giving up a meaningful difference?', practice: 'Name one idea you want to question and one person whose experience you want to hear.' },
  Pisces: { keywords: ['imagination', 'compassion', 'receptivity'], gift: 'imagination and care with room for boundaries', shadow: 'losing your own needs in someone else’s experience', style: 'imagination, sensitivity, and an openness to meaning', question: 'Where would a clearer boundary make compassion more sustainable?', practice: 'Enjoy a quiet creative moment, then name one practical need of your own.' },
};

export const ZODIAC = Object.fromEntries(Object.entries(SIGNS).map(([name, sign]) => [name, {
  ...sign, ...signAttributes(name),
  sun: `With the Sun in ${name}, explore purpose through ${sign.style}. A possibility to develop is ${sign.gift}; a tension to notice is ${sign.shadow}. ${sign.question}`,
  moon: `With the Moon in ${name}, consider how ${sign.style} might help you recognize and care for your emotional needs. Your own experience can confirm or challenge that suggestion. ${sign.question}`,
  rising: `${name} Rising offers ${sign.style} as a way to consider your approach to unfamiliar situations. You can choose how much of that approach fits the situation in front of you.`,
  node: `The North Node in ${name} can serve as a prompt to explore ${sign.gift}. You decide whether this direction belongs in your life; it does not assign you a destiny.`,
}]));
